[package]
name = "drs"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.22", features = ["kv"] }
thiserror = "2.0.4"

[dev-dependencies]
pathfinding = "4.11.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
